### ISSUE TITLE
Obsolete `merge`, `setwithpath` and `include`

### ISSUE THREAD

**Issue by shawninder** [vigour-io/util#4]
I've already deprecated `merge` and `setwithpath` (basically just added a log warning the user that he should stop using them and a note in the docs). So they will be obsolete (completely removed) in version 2. We also want to remove `include`, because as with the two others, it can be replaced by lodash stuff. @marcusbesjes Jim thinks you're using `include` in various places. Can you confirm that it's easy to replace with lodash stuff?

**Comment by marcusbesjes** [comment]
yes `merge` and `include` are used in `vigour-config`, will replace them with lodash stuff now

**Comment by marcusbesjes** [comment]
I refactored so it no longer uses `vigour-util/merge`, but I couldnt really figure out what the lodash solution for `include` would be though, any thoughts @shawninder @jimdebeer ?

**Comment by shawninder** [comment]
I'm not really sure I understand the purpose of `include`, actually. It allows you to add an item to an array. If the item is a boolean, string or number, it just `push`es the item. If the item is an array, in `concat`s the arrays. And if the item is an object, it `push`es the values, losing the keys. But if any of these values is an object, you get the full object in the array instead, preserving the keys... In all cases it also prevents from inserting an item that's already there (except in the case of an object or array with objects inside). @marcusbesjes could you help me understand what the purpose is? And then we can see if there is a `lodash` way or if it's more useful than I originally thought and we can just add docs and tests and remove the deprecation notice.

**Comment by marcusbesjes** [comment]
include ensures an item is included in an Array, so
`include([1,2,3], 15) => [1,2,3,15] // pushes and returns mutated array`
while
`include([1,2,3], 3) => [1,2,3] // does not push and returns unchanged array`

Its a way to not have to check if something is already in an Array before pushing.

the list stuff is to be able to include multiple items in one go

`include([1,2,3], [2,3,4,'lurp']) => [1,2,3,4,'lurp'] // ignored 2 and 3 but added the others`

**Comment by shawninder** [comment]
It also does the following:
- `include([], { a: 1 }) => [1]`
- `include([1], { a: 1 }) => false`
- `include([1], { a: { b: 1 } }) => [2]`

This is the kind of thing that is confusing me, but maybe it's not intended behaviour?

**Comment by marcusbesjes** [comment]
yeah the return values are a bit weird, but the list is mutated as expected, and the general idea of the return value was that it should return false if it didn't add anything.

**Comment by marcusbesjes** [comment]
anyhoo, does lodash have something like this?

**Comment by shawninder** [comment]
And the last case which returns `[2]` is just a bug?

**Comment by marcusbesjes** [comment]
it looks like the result is that in the case where you feed it a list to include, it returns an array with one element, the new length (return value of push). Not sure if you want to call it a bug, as I said the goal of the return value was not to return the mutated array as i previously stated, but to return false if nothing was pushed, mutating the first argument is the main goal.

**Comment by shawninder** [comment]
Ah sorry I misunderstood because in all other cases it returns the mutated array...

**Comment by shawninder** [comment]
so yeah I don't think lodash has all these things bundled in a single function. I'm going to try to clean it up a bit, test it, document it, and remove the deprecation notice

**Comment by marcusbesjes** [comment]
~~no it never returns the mutated array, forget I said that~~ never mind the return values are weird

**Comment by shawninder** [comment]
hmm, I thought I had observed this, but I'm wrong
